#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
 
use Symfony\Component\Console\Application;
use CH\Commands\HelloWorld;

$app = new Application();
$app->add(new HelloWorld());
$app->run();